baseurl: "https://silvela.org/jaime/lost/"
canonifyurls: true
disablePathToLower: true
languageCode: "en-us"
title: "Lost Among Europeans"
author: "Jaime Silvela"
theme: "lost"
disqusShortname: "lostamong"

params:
  copyright: "Jaime Silvela"
  twitter: "https://twitter.com/jsilvela"
  email: "jaime.silvela@gmail.com"

...